import React, { useState, useEffect } from 'react';
import { AnalysisResult } from '../types';
import { ScoreCircle, RedFlagCard } from './HomePage';

const SharePage: React.FC = () => {
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const hash = window.location.hash;
    if (hash.startsWith('#share=')) {
      try {
        const encoded = hash.substring(7);
        const decoded = JSON.parse(atob(encoded));
        setResult(decoded);
      } catch (e) {
        console.error("Failed to parse shared data from URL", e);
        setError("Could not load the shared analysis. The link may be corrupted or invalid.");
      }
    } else {
        setError("No analysis data found in the link.");
    }
  }, []);

  if (error) {
    return (
      <div className="text-center p-8 bg-slate-800/50 rounded-lg">
        <span className="text-5xl mx-auto mb-4">😢</span>
        <h2 className="text-2xl font-bold text-red-400">Error Loading Report</h2>
        <p className="text-slate-400 mt-2">{error}</p>
        <a href="#home" className="mt-6 inline-block bg-indigo-600 text-white font-semibold py-2 px-4 rounded-md hover:bg-indigo-500">
            Back to Home
        </a>
      </div>
    );
  }

  if (!result) {
    return (
      <div className="text-center p-8">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-indigo-400 mx-auto"></div>
        <p className="mt-4 text-slate-400">Loading analysis report...</p>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto animate-fade-in-up">
        <header className="text-center mb-10">
            <a href="#home" className="text-white font-bold text-xl flex items-center gap-2 justify-center">
                <span className="text-2xl">🚩</span>
                <span>No-Code Red Flags</span>
            </a>
            <p className="text-slate-400 mt-2">AI-Generated Startup Idea Analysis Report</p>
        </header>

        <div className="space-y-8">
            <div className="bg-slate-800/50 rounded-xl p-6 border border-slate-700/50">
                <h2 className="text-2xl font-bold text-center mb-4">Validation Score</h2>
                <div className="flex flex-col md:flex-row items-center justify-center gap-6">
                    <ScoreCircle score={result.validationScore} />
                    <div className="flex-1 text-center md:text-left">
                        <p className="text-slate-300 font-medium">{result.scoreRationale}</p>
                        <p className="mt-4 text-slate-400 text-sm">{result.summary}</p>
                    </div>
                </div>
            </div>
            
            <div>
                <h2 className="text-2xl font-bold mb-4">Identified Red Flags</h2>
                <div className="space-y-4">
                    {result.redFlags.map((flag, index) => (
                        <RedFlagCard key={index} flag={flag} index={index} />
                    ))}
                </div>
            </div>

            <footer className="text-center mt-12 text-sm text-slate-500">
                <p>This report was generated by the No-Code Red Flags AI validator.</p>
                <a href="#home" className="text-indigo-400 hover:underline">Analyze your own idea</a>
            </footer>
        </div>
    </div>
  );
};

export default SharePage;
